# Dependencies
#markdown:         redcarpet
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Abhijeet Chopra
tagline:          GitHub Website
description:      'CS Major and aspiring Computer Scientist'
url:              https://abhijeetchopra.github.io
baseurl:          /

author:
  name:           'Abhijeet Chopra'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
